### PR TITLE
Update Platforms

### PR DESCRIPTION
**Pull request by Jetup13**
* Add `megaduck` & `g7400`
* Add Duckstation (Legacy) to `psx` platform for those using Duckstation Legacy app

### CODE REVIEW

**Comment by Jetup13** [comment]
For Duckstation Legacy apk I wasn't sure what the uid should be.

**Comment by TapiocaFox** [comment]
> For [Duckstation Legacy](https://www.duckstation.org/android/) apk I wasn't sure what the uid should be.

Thanks for the pull request. Lemme do some research. :3

**Comment by Jetup13** [comment]
Thanks!

Noticed the Videopac+ G7400 was changed to Magnavox Odyssey 2. They're actually two different systems. G7400 was released only Europe (it was the successor to the Odyssey 2, which was also called Videopac in Europe). 

I wanted to close #445 . Or did you want to combine it with Odyssey 2? (Which is already available)

**Comment by TapiocaFox** [comment]
Hello brother. I've followed the naming scheme from Retropie. And I thought they all share the same emulator. Perhaps a more generic naming will be better? So that it includes the consoles which the emulator supports, especially, consider that the ROM sets aren't very big, so it is better to combine them anyway. For instance, like "Philips VideoPac".

**Comment by TapiocaFox** [comment]
Hold on a second. There is odyssey 2 already.

**Comment by TapiocaFox** [comment]
Your naming scheme is 100% better. I am gonna revert it back. Thanks for the help brother!

**Pull request merged**
