### PR TITLE
Update Nintendo3DS.json for Citra MMJ Antutu

### PR DESCRIPTION
**Pull request by mjkaye**
Correct file.path to file.uri for Citra MMJ Antutu.

### CODE REVIEW

**Comment by Jetup13** [comment]
file.path seems to work fine as file.uri does not launch into a game. Used the latest build [here](https://github.com/weihuoya/citra/releases). Are you using a different build?

**Comment by mjkaye** [comment]
> file.path seems to work fine as file.uri does not launch into a game. Used the latest build [here](https://github.com/weihuoya/citra/releases). Are you using a different build?

Thanks for looking at this.

I've updated today (my build was a couple of weeks old) but, for me, it's still the case that `file.uri` works (launches a game) and `file.path` does not. I used the "StorageAccess_Antutu" version because the ROMs are stored on an SD card.

For more specifics, this is on an Anbernic RG405M running GammaOS (LineageOS 19.1/Android 12).

Can I ask which version of Android you're running?

**Comment by Jetup13** [comment]
Retroid Pocket 3+ (A11) & Samsung S10e (A12). Tried storage access antutu and file.uri worked. Since they are two different builds and use different launch commands I'll create a separate player for storage antutu version. 

I'll close this merge in the meantime

**Comment by mjkaye** [comment]
Thank you for taking care of that. Your new player works as advertised.

So that I might produce better PRs in future, could I ask you educate me about the difference between `file.path` and `file.uri`?

**Comment by Jetup13** [comment]
`{file.path}` = raw path of rom

Example:

> /storage/emulated/0/roms/nds/Yu-Gi-Oh! - World Championship 2007 (USA) (En,Ja).zip

`{file.uri}` = path of rom in uri format

Example:

> content://com.android.externalstorage.documents/tree/primary%3Aroms%2Fnds/document/primary%3Aroms%2Fnds&2FYu-Gi-Oh!%20-%20World%20Championship%202007%20(USA)%20(En%2CJa).zip

A good indicator that an app will use `{file.uri}` is if it brings up the Files app when adding paths (giving permissions to a folder) within app

**Comment by mjkaye** [comment]
Thank you. That's a concise, and very helpful, explanation.

**Pull request closed without merging**
