### PR TITLE
New theme port of colorful by viking 

### PR DESCRIPTION
**Pull request by Jamesinorbit**
Hey, I felt the colorful theme by Viking deserved some love so I built out a more expanded set based on all the resources available...100+ systems. Thanks very much

### CODE REVIEW

**Comment by Post-Mortem** [comment]
@Jamesinorbit i noticed you index file is missing the   "matchPlatformUniqueId" text on each platform, i'm verifying if this is needed for the theme to work or if the text will be added automatically after i merge it. Please wait.

**Comment by Jamesinorbit** [comment]
sorry, i just used one of my previous index files as the base and amended it. Please fix it if possible. Thanks mate

**Comment by Jamesinorbit** [comment]
do u want me to redo the index file? Or can u amend it? thanks J

**Comment by Post-Mortem** [comment]
> do u want me to redo the index file? Or can u amend it? thanks J

Yes, you can just edit the index file and the pull request will be updated.

**Comment by Jamesinorbit** [comment]
Hey, looks like the index file has been updated by yourself but the theme isn't appearing in the download list in the app just to make you aware...thanks so much mate

**Comment by EgoBizarro** [comment]
Oooooh, nice! Thanks for these! 
I've already found the pack in the app and downloaded, but a lot of them don't seem to work. I guess there's still something not quite right with the index file or something.

**Comment by Post-Mortem** [comment]
> Oooooh, nice! Thanks for these! I've already found the pack in the app and downloaded, but a lot of them don't seem to work. I guess there's still something not quite right with the index file or something.

weird, i can see all wallpapers here: https://daijishou.github.io/Gallery/wallpapers_pack#Colorfully

**Pull request merged**
